### ISSUE TITLE
Test script failure on mac

### ISSUE THREAD

**Issue by jatkinson1000** [jakelangham/kestrel#12]
The test script fails on mac due to there not being an `ldd` command ([line 50, `tests/runall.jl`](https://github.com/jakelangham/kestrel/blob/022fe65f9ff0b1852f6875fcffecbf3954b751f7/tests/runall.jl#L50)) on mac OS.

This can be resolved by using `otool -L` in place of `ldd`, and indeed, if I do this the tests run fine.

Consider making this point in the documentation, or implementing both in julia (OS detection, or try and except with `ldd`)?

Discovered as part of https://github.com/openjournals/joss-reviews/issues/6079

**Comment by jatkinson1000** [comment]
@jakelangham Mostly good, just a small fix that I have submitted in PR #13

**Comment by jakelangham** [comment]
@jatkinson1000 Thanks for fixing that directly, really appreciated.
