### ISSUE TITLE
Include version in RunInfo

### ISSUE THREAD

**Issue by jakelangham** [jakelangham/kestrel#2]
It would be good to record version info in RunInfo.txt in order to make debugging issues easier when they arise.

Ideally we would record a major/minor version number and a git commit checksum. It should be possible to bake this in at compile time.

Hardly top priority, but it sill seems better to do this sooner rather than later.

**Comment by markwoodhouse** [comment]
Agree, this would be good.

If you are able to do this for txt files, I'll can then add as attributes in netcdf files too.

Perhaps they could be elements in RunParams to make that easy?

**Comment by jakelangham** [comment]
https://github.com/jakelangham/kestrel/pull/32 resolves this
