### ISSUE TITLE
Problems locating proj

### ISSUE THREAD

**Issue by jatkinson1000** [jakelangham/kestrel#8]
Hi there, I'm trying to install this software following the instructions in the README, but am having issues at compile with linking to proj.

I have installed proj and can see it on my system:
```
[user@machine kestrel]$ proj
Rel. 9.3.0, September 1st, 2023
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]
```

But trying to build leads to the error:
```
...
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands
Making all in src
g++ -std=c++17 -DPACKAGE_NAME=\"Kestrel\" -DPACKAGE_TARNAME=\"kestrel\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"Kestrel\ 1.0\" -DPACKAGE_BUGREPORT=\"Mark.Woodhouse@bristol.ac.uk,\ J.Langham@bristol.ac.uk\" -DPACKAGE_URL=\"\" -DPACKAGE=\"kestrel\" -DVERSION=\"1.0\" -DHAVE_CXX17=1 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_FILESYSTEM=1 -DHAVE_GDAL=1 -DHAVE_GDAL_OGR=1 -DHAVE_NETCDF4=1 -I.    -Wall -I/opt/homebrew/Cellar/gdal/3.8.0/include  -O2 -falign-loops=16  -g -O2 -MT kestrel-cUTM.o -MD -MP -MF .deps/kestrel-cUTM.Tpo -c -o kestrel-cUTM.o `test -f 'cUTM.cpp' || echo './'`cUTM.cpp
In file included from cUTM.cpp:25:
./cUTM.h:31:10: fatal error: 'proj.h' file not found
#include "proj.h"
         ^~~~~~~~
1 error generated.
make[1]: *** [kestrel-cUTM.o] Error 1
make: *** [all-recursive] Error 1
```

Any help you might provide would be appreciated.

I also noted that I had to install automake to execute autoreconf, so you could consider adding it to the list of dependencies.

**Comment by jakelangham** [comment]
This is quite a timely bug report since I noticed a bit of an issue with this today. If we are lucky, it's related to this

https://github.com/jakelangham/kestrel/issues/7

Could you please check the output of configure and see if it really found PROJ? If not, it may be in a nonstandard location like /opt/proj and you will need to run configure with the option

./configure --with-proj=[path-to-base-proj-dir]

This should have been in the installation documentation but I must have skipped over it in haste. (Hence the bug report.)

p.s. re automake - the dependencies list in the documentation mentions GNU autotools, but I can update that to clarify.

**Comment by jatkinson1000** [comment]
Aha!
`config.log` indeed suggests it wasn't located!
`./configure --with-proj=/opt/homebrew/Cellar/proj/9.3.0` is correctly locating and linking.

Next issues is that I get a `Fatal Error: Cannot open module file 'netcdf.mod' for reading` even though it is listed as an optional dependency.
This (and the automake point) may be covered in more depth in the full docs which I'll take a look at - I have only been working on the quick-start for the 'particularly impatient' so far ;)

Thanks for the fast response - in general this has gone a lot more smoothly than a lot of research software I see!

**Comment by jatkinson1000** [comment]
The `netcdf` error can be resolved by installing `netcdf-fortran` in addition to base `netcdf`.

**Comment by jakelangham** [comment]
I see. We build with NetCDF by default if it's found, so perhaps this is indicating that we need to add this to the macro that checks for NetCDF support. Thanks - I will look into this tomorrow. Did you make it to a working executable?

**Comment by jatkinson1000** [comment]
So, I had NetCDF installed, but not NetCDF-Fortran, so maybe check for both is required.

There is _an_ executable, I'll look tomorrow to see if it works!

**Comment by jakelangham** [comment]
I've made various changes to the build system and docs to address the issues raised here this morning (2d6571f721e1c7494f695fb623405fefa5631bfc, 18fa79eca739d6ded72cfdafec7e7bde8888928d, 06d96d3f3121b99c493596cd77a457054be872ed, 7f04540ee51b33757fcf1caf32cdeb06fe0e3f60), so going to mark this closed.
